#!/bin/bash

if [ "$#" -ne 1 ]; then
    IMAGE_TYPE=docker
else
    IMAGE_TYPE=$1
fi

IMAGE_NAME="robotica:$IMAGE_TYPE"
CONTAINER_NAME="robotica_$IMAGE_TYPE"

xhost +local:docker

docker run -it --rm \
    --privileged \
    --network host \
    --env DISPLAY \
    --volume $HOME/.bash_history:/home/robotica/.bash_history:rw \
    --volume $HOME/.Xauthority:/home/robotica/.Xauthority:rw \
    --volume /tmp/.X11-unix:/tmp/.X11-unix:rw \
    --user $(id -u $USER):$(id -g $USER) \
    --volume $HOME/catkin_ws:/home/robotica/catkin_ws \
    --volume $HOME/colcon_ws:/home/robotica/colcon_ws \
    --gpus all \
    --workdir /home/robotica \
    --name $CONTAINER_NAME \
    $IMAGE_NAME bash

xhost -local:docker
